// Centralized translation and question engine

const translations = {
    english: {
        title: "Patient Case Intake",
        select_language: "Please select your preferred language",
        btn_next: "Next",
        btn_prev: "Previous",
        btn_submit: "Review & Submit",
        not_sure: "Not sure",
        yes: "Yes",
        no: "No",
        consent_q: "Do you consent to sharing this health information with your doctor?",
        details_q: "Basic Details (Height, Weight, Blood Group)",
        department_q: "Which department are you visiting?",
        chief_complaint_q: "What is your main health problem?",
        history_q: "History of Present Illness (When did it start, severity, etc.)",
        past_medical_q: "Past Medical History (Any chronic diseases like Diabetes, Hypertension?)",
        past_surgical_q: "Past Surgical History (Any previous surgeries?)",
        medications_q: "Current Medications (Are you taking any medicines?)",
        allergies_q: "Allergies (Do you have any known allergies?)",
        family_history_q: "Family History (Any hereditary diseases in your family?)",
        personal_history_q: "Personal History (Smoking, alcohol, diet habits)",
        ros_q: "Review of Systems (Any other symptoms like fever, fatigue, weight loss?)",
        documents_q: "Previous Documents (Note: Upload feature coming soon)",
        review_title: "Review Your Information"
    },
    hindi: {
        title: "मरीज केस जानकारी",
        select_language: "कृपया अपनी पसंदीदा भाषा चुनें",
        btn_next: "अगला",
        btn_prev: "पिछला",
        btn_submit: "समीक्षा और सबमिट करें",
        not_sure: "पक्का नहीं",
        yes: "हाँ",
        no: "नहीं",
        consent_q: "क्या आप इस स्वास्थ्य जानकारी को अपने डॉक्टर के साथ साझा करने की सहमति देते हैं?",
        details_q: "मूल विवरण (ऊंचाई, वजन, रक्त समूह)",
        department_q: "आप किस विभाग में जा रहे हैं?",
        chief_complaint_q: "आपकी मुख्य स्वास्थ्य समस्या क्या है?",
        history_q: "वर्तमान बीमारी का इतिहास (यह कब शुरू हुआ, गंभीरता आदि)",
        past_medical_q: "पिछला चिकित्सा इतिहास (कोई पुरानी बीमारी?)",
        past_surgical_q: "पिछला सर्जिकल इतिहास (कोई पिछली सर्जरी?)",
        medications_q: "वर्तमान दवाएं (क्या आप कोई दवा ले रहे हैं?)",
        allergies_q: "एलर्जी (क्या आपको कोई ज्ञात एलर्जी है?)",
        family_history_q: "पारिवारिक इतिहास (आपके परिवार में कोई वंशानुगत बीमारी?)",
        personal_history_q: "व्यक्तिगत इतिहास (धूम्रपान, शराब, आहार की आदतें)",
        ros_q: "सिस्टम की समीक्षा (कोई अन्य लक्षण?)",
        documents_q: "पिछले दस्तावेज़",
        review_title: "अपनी जानकारी की समीक्षा करें"
    },
    telugu: {
        title: "రోగి కేసు సమాచారం",
        select_language: "దయచేసి మీకు ఇష్టమైన భాషను ఎంచుకోండి",
        btn_next: "తరువాత",
        btn_prev: "గత",
        btn_submit: "సమీక్షించి సమర్పించండి",
        not_sure: "ఖచ్చితంగా తెలియదు",
        yes: "అవును",
        no: "కాదు",
        consent_q: "ఈ ఆరోగ్య సమాచారాన్ని మీ వైద్యుడితో పంచుకోవడానికి మీరు అంగీకరిస్తున్నారా?",
        details_q: "ప్రాథమిక వివరాలు (ఎత్తు, బరువు, రక్తపు గ్రూపు)",
        department_q: "మీరు ఏ విభాగాన్ని సందర్శిస్తున్నారు?",
        chief_complaint_q: "మీ ప్రధాన ఆరోగ్య సమస్య ఏమిటి?",
        history_q: "ప్రస్తుత అనారోగ్య చరిత్ర",
        past_medical_q: "గత వైద్య చరిత్ర (ఏవైనా దీర్ఘకాలిక వ్యాధులు ఉన్నాయా?)",
        past_surgical_q: "గత శస్త్రచికిత్స చరిత్ర",
        medications_q: "ప్రస్తుత మందులు",
        allergies_q: "అలెర్జీలు",
        family_history_q: "కుటుంబ చరిత్ర",
        personal_history_q: "వ్యక్తిగత చరిత్ర",
        ros_q: "వ్యవస్థల సమీక్ష",
        documents_q: "గత పత్రాలు",
        review_title: "మీ సమాచారాన్ని సమీక్షించండి"
    }
};

const caseQuestions = [
    { id: "consent", type: "yes_no_details", translationKey: "consent_q" },
    { id: "patient_details", type: "text", translationKey: "details_q" },
    { id: "department", type: "text", translationKey: "department_q" },
    { id: "chief_complaint", type: "text", translationKey: "chief_complaint_q" },
    { id: "history_present_illness", type: "text", translationKey: "history_q" },
    { id: "past_medical_history", type: "yes_no_details", translationKey: "past_medical_q" },
    { id: "past_surgical_history", type: "yes_no_details", translationKey: "past_surgical_q" },
    { id: "medications", type: "yes_no_details", translationKey: "medications_q" },
    { id: "allergies", type: "yes_no_details", translationKey: "allergies_q" },
    { id: "family_history", type: "yes_no_details", translationKey: "family_history_q" },
    { id: "personal_history", type: "text", translationKey: "personal_history_q" },
    { id: "review_of_systems", type: "text", translationKey: "ros_q" },
    { id: "documents", type: "text", translationKey: "documents_q" }
];
